[package]
name = "container-rs"
version = "0.1.0"
authors = ["Nazım Can Altınova <canaltinova@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.17.0"
log = "0.4"
pretty_env_logger = "0.4"